[workspace]
members = [".", "xproc-macros"]
default-members = ["."]

[workspace.package]
version = "0.1.0"
edition = "2024"
# this is the first version of rust that supports 2024 edition
rust-version = "1.85.0"

[package]
name = "xproc"
version.workspace = true
edition.workspace = true

[dependencies]
xproc-macros = { path = "xproc-macros" }

[target.'cfg(windows)'.dependencies]
windows = { version = "0.62.2", features = ["Win32_Security", "Win32_Storage_FileSystem", "Win32_System_IO", "Win32_System_Threading"] }
windows-core = "0.62.2"

[target.'cfg(unix)'.dependencies]
libc = "0.2.186"
